services:
  robiki-proxy:
    container_name: "robiki-proxy"
    build:
      context: ./src
      dockerfile: ./../.docker/dockerfiles/prod.dockerfile
    ports:
      - "443:443"
      - "8080:8080"
      - "9229:9229"
    environment:
      - NODE_ENV=production
    volumes:
      - robiki-proxy:/usr/src
volumes:
  robiki-proxy:
